services:
  server:
    image: canary-wizard-local:dev
    platform: linux/arm64
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    volumes:
      - server-data:/data
      - ../data/scripts:/canary/data/scripts
