services:
  server:
    image: wizard-canary-local:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    volumes:
      - ../data/wizard:/canary/data/wizard:ro
      - ../data/scripts:/canary/data/scripts:ro
